### ISSUE TITLE
Some problems encountered during training

### ISSUE THREAD

**Issue by jdyjjj** [seoha-kim/Sync-NeRF#2]
Amazing job! I encountered some issues while trying to use this project and I really hope to receive your help.
My command is here:
```
 python train.py --config configs/plenoptic/sear_steak.txt
```
Traceback (most recent call last):
  File "/home/jdy/nerf/Sync-NeRF/Sync-MixVoxels/train.py", line 1324, in <module>
    reconstruction(args)
  File "/home/jdy/nerf/Sync-NeRF/Sync-MixVoxels/train.py", line 231, in reconstruction
    train_dataset = dataset(args.datadir, split='train', downsample=args.downsample_train, is_stack=False, white_bg = args.chromakey,
  File "/home/jdy/nerf/Sync-NeRF/Sync-MixVoxels/dataLoader/llff_video.py", line 295, in __init__
    self.read_meta(no_load, optimize_test)
  File "/home/jdy/nerf/Sync-NeRF/Sync-MixVoxels/dataLoader/llff_video.py", line 307, in read_meta
    poses_bounds = np.load(os.path.join(self.root_dir, 'poses_bounds.npy'))  # (N_images, 17)
  File "/home/jdy/anaconda3/envs/syncnerf/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/data2/jdy/nerf/syncnerf/plenoptic_unsync/poses_bounds.npy'

I want to know how to get poses_bounds.npy. Thanks!

**Comment by seoha-kim** [comment]
Hello.
I appreciate your interest in my research.

You can get poses_bounds.npy from [the orignial repo](https://github.com/facebookresearch/Neural_3D_Video/releases/tag/v1.0).
I have uploaded the pose to my Google Drive, too.
Please check it out and let me know if there is a problem.

**Comment by jdyjjj** [comment]
Thank you very much for your prompt response; it has been very helpful. However, I have another question regarding the plenoptic_unsync dataset. All the files in plenoptic_unsync are in mp4 format. Should I convert these mp4 files to the png format used in blender_unsync? Thank you very much for your assistance.

**Comment by seoha-kim** [comment]
You can convert from .mp4 file to .png file using ffmpeg 🙂

**Comment by jdyjjj** [comment]
Thank you very much for your assistance. I followed your advice and made the necessary adjustments, but encountered a small issue during the process:
![image](https://github.com/seoha-kim/Sync-NeRF/assets/73057174/164ffba3-c7d8-4c82-b326-d84d341febb2)
This looks like I need the 'camxx_std.npy' file. Could you please guide me on how to generate or obtain these '_std.npy' files? Thank you very much!
